import type { HogwartsArticle } from './hogwarts.lore';

export const HOGWARTS_COMMERCE_LESSONS: HogwartsArticle[] = [
  {
    title: 'Lesson 1: Curiosity Before Charms',
    subtitle: 'How to start a sales conversation without feeling pushy.',
    tag: 'Commerce Lessons',
    body: [
      'In the castle, the loudest spells are rarely the strongest. The best magic begins with attention: seeing what is happening in front of you before you try to change it.',
      'Sales works the same way. If you open with a pitch, you force the conversation onto rails that the other person did not choose. If you open with curiosity, you invite them to lead.',
      'Curiosity is not a trick. It is a posture: I want to understand your world before I offer mine. That single shift removes most of the shame and stiffness technical people feel.',
      'Start with one calm question that makes it safe to answer. Not a trap question. Not a closing question. A real one.',
      'Good first questions sound like this: What are you trying to achieve this month? Where does the current process feel slow? What would a good outcome look like for you?',
      'Notice how none of these asks for a commitment. They ask for a story. People like telling true stories about their work, especially when the listener is steady and respectful.',
      'When they answer, do not interrupt to prove you are smart. Take a beat. Summarize back what you heard. This is the first trust deposit.',
      'Then ask the second question: What have you already tried? This reveals constraints, politics, and hidden goals without you needing to guess.',
      'If you are shy, create a tiny script you can rely on. Your job is not to be witty. Your job is to be consistent.',
      'Pocket spell: I can suggest options, but first I want to understand. What is the main thing you are trying to improve right now?',
      '5-minute drill: Write five first questions. Say them out loud once each. Pick the one that feels most natural. Use it on the next call, even if your voice shakes.',
    ],
  },
  {
    title: 'Lesson 2: The Customers Quest (Job to Be Done)',
    subtitle: 'People do not buy products. They hire solutions.',
    tag: 'Commerce Lessons',
    body: [
      'A new student often thinks the wand is the magic. Then they learn: the wand is a tool, and the magic is the intention behind it.',
      'In commerce, the product is the wand. The customer is not shopping for features; they are trying to complete a quest.',
      'The quest might be obvious: reduce downtime, ship faster, avoid errors. Or it might be quiet: feel in control again, stop being blamed, look competent to the boss.',
      'Your task is to name the quest with them. When the quest is clear, the sale becomes a fit check instead of a performance.',
      'Ask: What will be different after this is solved? How will you measure success? Who else cares about this outcome?',
      'Then listen for the true constraint. Sometimes it is budget. Sometimes it is approval. Often it is time, attention, or fear of change.',
      'Once you know the quest, you can map your offer into it. Not as a list of features, but as steps in their story.',
      'Example: Instead of saying, We integrate with X, say, This removes the manual step that is costing you two hours every morning.',
      'This is especially helpful if you feel shy. You do not need to be loud. You just need to be precise about what changes.',
      'Pocket spell: If this works perfectly, what does your day look like two weeks from now?',
      '5-minute drill: Pick one customer you remember. Write the quest in one sentence. Write the hidden quest in one sentence. Decide which one matters more.',
    ],
  },
  {
    title: 'Lesson 3: The Three Gates (Fit, Timing, Authority)',
    subtitle: 'Qualify gently so you do not waste your own courage.',
    tag: 'Commerce Lessons',
    body: [
      'The castle has doors that open only for the right person at the right time. Commerce has gates too, and respecting them protects your energy.',
      'Gate one is fit: can your offer realistically solve the problem? If not, do not force it. A polite no is better than a messy yes.',
      'Gate two is timing: even a perfect solution fails when the buyer is not ready. Timing is not an excuse; it is a real constraint.',
      'Gate three is authority: who can say yes, and who can block the decision? Authority is often distributed, and your job is to map it.',
      'You can ask these without sounding aggressive. The tone is, I want to be respectful of your time and mine.',
      'Try: How are decisions like this usually made in your team? Is there a deadline we should be aware of? Who else should be in the room so we do not loop later?',
      'If you are shy, remember: asking these questions is not pressure. It is professionalism.',
      'When you qualify well, you feel calmer. Your brain stops trying to win every interaction because you are no longer treating every conversation like it must become a sale.',
      'Sometimes the outcome is a graceful exit. That is not failure. That is good sorting.',
      'Pocket spell: Before we go deeper, can I ask how you evaluate and decide on something like this?',
      '5-minute drill: Write one sentence for each gate: fit, timing, authority. Practice saying them in a neutral, friendly voice.',
    ],
  },
  {
    title: 'Lesson 4: The 70/30 Rule',
    subtitle: 'Talk less, listen more, and you will sound smarter.',
    tag: 'Commerce Lessons',
    body: [
      'In a duel, the frantic wizard swings too much and misses. The calm wizard waits, watches, and casts once with purpose.',
      'In sales, frantic talking is the same mistake. When you are nervous, you fill silence with information. The buyer hears noise.',
      'Aim for 70/30: they speak 70 percent of the time, you speak 30 percent. This is not a rigid rule, it is a calming target.',
      'Silence is not awkward when you treat it as thinking space. Ask a question, then let the silence do its work.',
      'If you worry they will judge you, anchor yourself with a note: I am here to learn. I do not need to impress.',
      'When they speak, your job is to harvest signal. Listen for pain, urgency, constraints, and language they repeat.',
      'Repeat their words back later. Not as mimicry, but as respect. People feel understood when you use their vocabulary.',
      'If you are technical, you have an advantage: you are already trained to debug by asking. Use that same skill on people.',
      'Pocket spell: Tell me more about that. What happens right before it becomes a problem?',
      '5-minute drill: On the next call, set a small goal: after every question, count to three in your head before you speak again.',
    ],
  },
  {
    title: 'Lesson 5: Evidence Over Claims',
    subtitle: 'Proof turns fear into confidence.',
    tag: 'Commerce Lessons',
    body: [
      'A spellbook can promise anything. The proof is whether the spell works when the candle flickers and your hand shakes.',
      'Buyers are not allergic to new ideas. They are allergic to risk. Your job is to reduce risk with evidence.',
      'Evidence can be a case study, a demo, a sample order, a trial period, or a clear explanation of what happens when something goes wrong.',
      'Do not drown them in numbers. Pick one or two pieces of proof that match their quest.',
      'If their pain is errors, show error reduction. If their pain is time, show time saved. If their pain is reputation, show reliability.',
      'When you present proof, narrate it like a story: where we started, what changed, what stayed the same, what we learned.',
      'For a shy seller, evidence is a gift. You do not have to be persuasive. You just show reality.',
      'Pocket spell: Would it help if I showed you a quick example of how this looks in practice?',
      '5-minute drill: Write down three proofs you already have: a screenshot, a metric, a customer quote. Store them where you can reach them fast.',
    ],
  },
  {
    title: 'Lesson 6: Price Is Context',
    subtitle: 'If it feels expensive, the comparison is missing.',
    tag: 'Commerce Lessons',
    body: [
      'A dragon egg costs more than a chicken egg, but nobody is surprised. The context explains the cost.',
      'When a buyer says it is expensive, they are not always rejecting you. They are asking: expensive compared to what?',
      'Your job is to surface the true comparison: the cost of mistakes, the cost of waiting, the cost of manual labor, the cost of a failed delivery.',
      'Do not argue. Ask one clarifying question. Then connect the price to the quest.',
      'Try: When you say expensive, what are you comparing it to? Another supplier, your current process, or the budget you set?',
      'Then you can frame tradeoffs: cheaper often means slower delivery, less support, more back-and-forth, or hidden failure costs.',
      'If you offer a discount, trade for something. A longer commitment, a smaller scope, a simpler SLA. Do not discount out of fear.',
      'Pocket spell: Help me understand what expensive means in your situation. What would feel reasonable, and why?',
      '5-minute drill: List three costs your customer already pays today. Convert one into RSD or hours per week. Keep it ready.',
    ],
  },
  {
    title: 'Lesson 7: The Two-Choice Table',
    subtitle: 'Do not overwhelm. Offer two or three clear paths.',
    tag: 'Commerce Lessons',
    body: [
      'A table of thirty potion ingredients does not help a beginner brew. A good professor selects the few that matter for this lesson.',
      'Buyers also freeze when presented with too many options. They fear choosing wrong.',
      'Offer two or three paths: safe, balanced, ambitious. Each path is defined by one or two differences, not a dozen.',
      'Name the tradeoff of each option in plain language: speed vs cost, flexibility vs simplicity, hands-on support vs self-serve.',
      'If you are technical, you may want to show all possibilities. Resist. Good selling is good pruning.',
      'Close the loop by asking preference: Which of these feels closest to what you want? Then refine.',
      'This style is gentle. It helps shy people because it turns selling into guiding.',
      'Pocket spell: I can propose two ways to do this: the simple path and the robust path. Which direction fits you better?',
      '5-minute drill: Take your offer and write two versions: a minimal starter and a robust version. Write one sentence that differentiates them.',
    ],
  },
  {
    title: 'Lesson 8: Objections Are Questions',
    subtitle: 'Treat resistance as information, not rejection.',
    tag: 'Commerce Lessons',
    body: [
      'When a broom bucks, it is not insulting you. It is telling you something about balance.',
      'Objections work the same way. A buyer says no because they are protecting something: money, time, reputation, safety.',
      'Your job is to discover what they are protecting and name it with respect.',
      'Use a label: It sounds like you are worried about implementation risk. Then pause. Let them confirm or correct.',
      'Once the real worry is visible, you can address it with proof, process, or a smaller step.',
      'Never rush to defend yourself. Defense makes you sound guilty, even when you are not.',
      'For shy people, objections feel like conflict. Reframe them: they are collaboration. The buyer is helping you see what matters.',
      'Pocket spell: That makes sense. Can I ask what is behind that concern so I respond to the right thing?',
      '5-minute drill: Write your top five objections. For each, write one clarifying question and one calm answer.',
    ],
  },
  {
    title: 'Lesson 9: The Next Step Spell',
    subtitle: 'Every good conversation ends with a clear next move.',
    tag: 'Commerce Lessons',
    body: [
      'A lesson without homework fades. A conversation without a next step dissolves into polite memory.',
      'Your goal is not to close every call. Your goal is to move the deal one step forward with clarity.',
      'A next step can be: a demo, a sample quote, a stakeholder meeting, a trial order, a technical check, or a simple follow-up date.',
      'Make it specific: Tuesday at 10, send the list of parts, meet with procurement, test one category.',
      'If you feel shy, this is your anchor. It gives you structure and reduces the fear of ending the call awkwardly.',
      'Ask for agreement: Does that work for you? Then confirm in writing.',
      'When you do this consistently, your confidence grows because you stop guessing what happens next.',
      'Pocket spell: If we want to be practical, what is the next small step that would give you confidence?',
      '5-minute drill: Create a list of five next steps you can offer. Keep them on your desk. Use one every time.',
    ],
  },
  {
    title: 'Lesson 10: The Gentle Follow-Up',
    subtitle: 'Persistence without pressure.',
    tag: 'Commerce Lessons',
    body: [
      'Owls do not apologize for delivering messages. They arrive, perch, and wait. Calm persistence is not aggression.',
      'Most deals do not move because the buyer is busy, not because they hate you. Follow-up is a service: it keeps the thread alive.',
      'A good follow-up has value. It is not, Just checking in. It is: Here is the summary, here is one helpful idea, here is the next step.',
      'Use short, clear messages. Respect their attention.',
      'If you feel shame around follow-up, rename it: I am helping them finish a decision they already started.',
      'Do not chase forever. Set a boundary. If there is no response after a clear number of attempts, close the loop politely.',
      'Pocket spell: Quick note with the summary and the next step. If the timing is not right, tell me and I will pause.',
      '5-minute drill: Write a follow-up template with three lines: recap, value, question. Save it and reuse it.',
    ],
  },
  {
    title: 'Lesson 11: The First Contact Script',
    subtitle: 'A simple opening for shy technical founders.',
    tag: 'Commerce Lessons',
    body: [
      'You do not need a grand speech. You need a door that opens.',
      'A good first contact script is short, specific, and respectful. It names who you are, why you reached out, and invites a small reply.',
      'Avoid large claims. Avoid pressure. Your goal is a conversation, not a contract.',
      'Example structure: observation, hypothesis, question.',
      'Observation: I noticed you do X. Hypothesis: that might create Y cost. Question: is this true for you?',
      'Technical people fear sounding silly. The trick is to make the question about them, not about your expertise.',
      'If they reply, you have permission to ask more. If they do not, you have saved your energy for a better fit.',
      'Pocket spell: I might be wrong, but is this a problem for you: [one sentence]? If yes, happy to share what we have seen work.',
      '5-minute drill: Write three first messages for three industries. Make each under 60 words.',
    ],
  },
  {
    title: 'Lesson 12: The Demo as Story',
    subtitle: 'Do not show features. Show transformation.',
    tag: 'Commerce Lessons',
    body: [
      'A good lesson is not a list of facts. It is a journey from confusion to clarity.',
      'A demo should be the same: start with the problem state, then walk to the solved state.',
      'Open with their words: You said the pain is delays and uncertainty. Today I will show how we shorten the path and make it visible.',
      'Then show only what matters. If you show everything, nothing feels important.',
      'Narrate your clicks with intent: this is where the error used to happen, this is how the system prevents it, this is the result.',
      'Invite them into the story. Ask: would this match your workflow? Where would it break? What would you change?',
      'Shy people often hide behind the screen. Instead, use the screen as a shared map.',
      'Pocket spell: I will keep this simple: before, during, after. Tell me where this matches your world and where it does not.',
      '5-minute drill: Write the three chapters of your demo: pain, change, result. Remove any slide that does not serve those chapters.',
    ],
  },
  {
    title: 'Lesson 13: The Risk-Removal Charm',
    subtitle: 'Why buyers hesitate and how to make it safe.',
    tag: 'Commerce Lessons',
    body: [
      'Most hesitation is not about desire. It is about fear.',
      'Fear of wasting money, fear of failing internally, fear of looking foolish, fear of being stuck with the wrong choice.',
      'You remove fear by making the decision reversible or by reducing the size of the first step.',
      'Offer a pilot, a small order, a staged rollout, or a clear exit clause. Show your support process. Show how problems are handled.',
      'If you do not have formal policies yet, you can still reduce risk with clarity: what happens if delivery is late, what happens if the data is wrong, who answers.',
      'This is not weakness. This is maturity.',
      'For shy people, risk removal helps you speak confidently because you are offering safety, not pressure.',
      'Pocket spell: What would make this feel safe to try? A smaller scope, a pilot, or a clear rollback plan?',
      '5-minute drill: Write your pilot offer in five bullets. One scope, one timeline, one success metric, one support promise, one exit.',
    ],
  },
  {
    title: 'Lesson 14: The Trade, Not the Discount',
    subtitle: 'Protect value while being flexible.',
    tag: 'Commerce Lessons',
    body: [
      'In the Great Hall, nothing is free. Even kindness has a cost: time, effort, attention.',
      'Discounting without a trade teaches buyers to ask for more pressure later. Trading teaches respect.',
      'If they want a lower price, adjust something real: scope, speed, service, payment terms, commitment length.',
      'You can say yes without shrinking yourself. You can be flexible without being shaky.',
      'A trade creates structure: if we reduce price, we reduce X. If we keep price, we include Y.',
      'This makes the conversation professional and calm, which helps if you feel self-conscious.',
      'Pocket spell: I can work with that. What would you prefer to trade: scope, timeline, or support level?',
      '5-minute drill: List three levers you can trade. Scope, SLA, delivery speed, payment terms. Decide what you will not trade.',
    ],
  },
  {
    title: 'Lesson 15: The One-Sentence Value',
    subtitle: 'A clear value line you can say without stress.',
    tag: 'Commerce Lessons',
    body: [
      'When you are nervous, your mind produces paragraphs. Buyers need one sentence.',
      'A good value sentence has three parts: for who, what outcome, by what mechanism.',
      'Example: For workshops that lose time on manual ordering, we reduce ordering mistakes by validating stock and pricing automatically.',
      'Notice how it is not poetic. It is practical.',
      'Your value sentence is not your whole story. It is the sign on the door that tells the right people to enter.',
      'If you are shy, rehearse the sentence until it feels boring. Boring is good. Boring means you can say it under pressure.',
      'Pocket spell: For [who], we help [outcome] by [how].',
      '5-minute drill: Write three versions of your value sentence. Read them out loud. Choose the simplest.',
    ],
  },
  {
    title: 'Lesson 16: The Mirror Summary',
    subtitle: 'Repeat back what you heard to build trust fast.',
    tag: 'Commerce Lessons',
    body: [
      'In Transfiguration, the mirror is unforgiving. It shows exactly what you did, not what you meant.',
      'In sales, a summary is a mirror. It shows the buyer you truly heard them.',
      'A good summary is short and specific: You want A, because B. The constraint is C. The success metric is D.',
      'Ask for confirmation: did I get it right? Then let them correct you.',
      'This removes confusion and reduces shame because you stop guessing what they meant.',
      'It also makes you sound senior, even if you feel nervous. Senior people summarize well.',
      'Pocket spell: Let me reflect what I heard to be sure I understood: [three bullets]. Is that accurate?',
      '5-minute drill: After your next meeting, write the summary in four lines. Send it as a follow-up.',
    ],
  },
  {
    title: 'Lesson 17: The Stakeholder Map',
    subtitle: 'Who says yes, who blocks, who influences.',
    tag: 'Commerce Lessons',
    body: [
      'A castle decision is never made by one portrait alone. There are whispers, permissions, and invisible politics.',
      'In commerce, stakeholders matter: the user, the buyer, the approver, the gatekeeper, the skeptic, the champion.',
      'Your job is to map who is who. Then you tailor the message: users care about ease, approvers care about risk, finance cares about predictability.',
      'Ask gently: who else cares about this outcome? Who will use it daily? Who signs? Who might object and why?',
      'When you include stakeholders early, deals move faster. When you ignore them, deals stall in silence.',
      'If you are shy, you may avoid asking these questions. Do not. It is not rude, it is respectful.',
      'Pocket spell: To avoid surprises later, who else should we include in the next step?',
      '5-minute drill: Draw a simple map with names and roles for one active customer. Identify your champion and your skeptic.',
    ],
  },
  {
    title: 'Lesson 18: The Micro-Commitment',
    subtitle: 'Ask for small yeses that feel safe.',
    tag: 'Commerce Lessons',
    body: [
      'A beginner does not start with advanced spells. They start with a small levitation and build confidence.',
      'Sales is the same. If you ask for a huge commitment too early, you trigger fear.',
      'Instead, ask for a micro-commitment: can we look at one example order, can we do a 15-minute check, can we test one category.',
      'Each small yes reduces uncertainty and creates momentum.',
      'This is perfect for shy people because you are not forcing a big moment. You are guiding small steps.',
      'Pocket spell: Instead of deciding today, would you be open to a small test so we both learn quickly?',
      '5-minute drill: Create three micro-commitments that match your product: demo, sample, pilot. Use one today.',
    ],
  },
  {
    title: 'Lesson 19: The Calm Close',
    subtitle: 'Closing without pressure: clarity, not conquest.',
    tag: 'Commerce Lessons',
    body: [
      'Closing is not an ambush. It is the moment you ask the buyer to choose a path.',
      'A calm close summarizes value, names the next step, and asks for agreement.',
      'You can also close by offering a choice: start small now, or schedule for next month.',
      'If they say no, you thank them and learn. If they say yes, you confirm details. Either way, you stay steady.',
      'Shame often shows up here: fear of being seen as salesy. Remember: clarity is kindness.',
      'Pocket spell: Based on what we discussed, are you comfortable moving forward with the pilot next week?',
      '5-minute drill: Write one closing line for three scenarios: eager buyer, unsure buyer, not now buyer.',
    ],
  },
  {
    title: 'Lesson 20: The Pipeline Lantern',
    subtitle: 'Track leads so you do not rely on memory.',
    tag: 'Commerce Lessons',
    body: [
      'A lantern does not make the corridor shorter, but it makes the path visible.',
      'A pipeline is that lantern. It shows where conversations are, what the next step is, and what is stuck.',
      'Keep it simple: lead, contacted, meeting, proposal, negotiation, won, lost.',
      'Write the next step and the date. If there is no next step, the deal is not real yet.',
      'This reduces anxiety because you stop carrying everything in your head.',
      'Pocket spell: My rule is simple: every opportunity must have a next step and a date.',
      '5-minute drill: Create a small table. Add five current leads. Add one next step for each.',
    ],
  },
  {
    title: 'Lesson 21: The Language of Outcomes',
    subtitle: 'Translate technical detail into business value.',
    tag: 'Commerce Lessons',
    body: [
      'Technical people speak in mechanisms. Business people listen for outcomes.',
      'You do not need to hide the mechanism. You need to connect it to the outcome.',
      'Mechanism: cache, queue, validation, retry. Outcome: faster, safer, fewer mistakes, less manual work.',
      'Practice the bridge sentence: This means you will see [outcome] because [mechanism].',
      'When you do this, you sound confident and helpful instead of complicated.',
      'Pocket spell: Under the hood it does X, which matters because it gives you Y.',
      '5-minute drill: Pick five features. For each, write one outcome sentence. Keep them on a note.',
    ],
  },
  {
    title: 'Lesson 22: The Trust Deposit',
    subtitle: 'Small acts that build long-term sales power.',
    tag: 'Commerce Lessons',
    body: [
      'The castle trusts students who return books, tell the truth, and show up when they say they will.',
      'Customers are the same. Trust is built with small deposits: punctuality, accurate summaries, honest constraints, fast responses.',
      'Never promise what you cannot deliver. It feels good in the moment and burns you later.',
      'If something goes wrong, name it early. Buyers forgive mistakes more than they forgive surprises.',
      'Shy people often over-promise to avoid conflict. Practice the opposite: calm honesty.',
      'Pocket spell: I want to be transparent: here is what we can do now, and here is what would take more time.',
      '5-minute drill: Write one sentence you can use to say no kindly. Practice it once.',
    ],
  },
  {
    title: 'Lesson 23: The Buyer Journal',
    subtitle: 'Remember what matters to each customer.',
    tag: 'Commerce Lessons',
    body: [
      'A journal turns chaos into narrative. Sales becomes calmer when you remember the human story behind each account.',
      'For each buyer, capture: their quest, their constraints, their language, their stakeholders, their fears, their win condition.',
      'This is not manipulation. It is respect. People feel safe when you remember what they told you.',
      'It also helps your confidence. You stop improvising and start continuing a story you already know.',
      'Pocket spell: Last time you mentioned X was the biggest pain. Is that still true this week?',
      '5-minute drill: For one active buyer, write five bullets in your journal. Use them in your next message.',
    ],
  },
  {
    title: 'Lesson 24: The Two-Email Proposal',
    subtitle: 'Short proposal first, details second.',
    tag: 'Commerce Lessons',
    body: [
      'Long scrolls intimidate. A clear letter invites.',
      'Send proposals in two layers: a short summary in the email body, and details in an attached document or link.',
      'The summary has: problem, approach, timeline, price, next step.',
      'If they want details, they can open them. If they do not, they still understand the decision.',
      'This reduces friction and increases replies.',
      'Pocket spell: Here is the short version in five bullets. If this looks right, I will send the detailed plan.',
      '5-minute drill: Rewrite your last proposal as five bullets. Remove anything that is not necessary for a decision.',
    ],
  },
  {
    title: 'Lesson 25: The Rejection Shield',
    subtitle: 'How to protect your confidence while learning.',
    tag: 'Commerce Lessons',
    body: [
      'A missed spell is not a verdict on your worth. It is feedback about technique.',
      'Rejection in sales feels personal, especially for shy people. But most no answers are about timing, budget, or priorities.',
      'Your job is to extract one lesson without self-attack.',
      'Ask one question: what made it a no? Then thank them. Then write the lesson in your journal.',
      'Over time, your nervous system learns that no is survivable. That is real courage.',
      'Pocket spell: Thank you for the clarity. For my learning, what was the main reason this was not a fit?',
      '5-minute drill: Write three reasons a buyer can say no that are not about you. Read them before your next call.',
    ],
  },
  {
    title: 'Lesson 26: The Courage Reps',
    subtitle: 'Small daily practice that dissolves shyness.',
    tag: 'Commerce Lessons',
    body: [
      'Confidence is not a personality. It is a muscle.',
      'You build it with tiny reps: one message sent, one question asked, one follow-up done politely.',
      'Do not wait to feel ready. Readiness comes after action.',
      'Set a daily minimum: two outreach messages, one follow-up, one learning note. Keep it small enough to do even on bad days.',
      'Celebrate completion, not outcomes.',
      'Pocket spell: Today I do the rep. Tomorrow I refine the rep.',
      '5-minute drill: Pick one daily rep for the next seven days. Write it on your calendar. Do it even if it feels awkward.',
    ],
  },
  {
    title: 'Lesson 27: The Referral Whisper',
    subtitle: 'Ask for introductions in a way that feels natural.',
    tag: 'Commerce Lessons',
    body: [
      'Referrals are the warmest corridor in the castle. Someone opens the door for you.',
      'The key is timing: ask after a small win, not before trust exists.',
      'Make the ask specific: who do you know that struggles with X? If you ask for anyone, you get no one.',
      'Also make it easy: a one-line introduction they can forward.',
      'Pocket spell: If you know one person who deals with X, would you be comfortable introducing us? I can draft the message.',
      '5-minute drill: Write a one-paragraph intro someone can forward. Keep it friendly and short.',
    ],
  },
  {
    title: 'Lesson 28: The After-Sale Spell',
    subtitle: 'Retention is the quiet superpower.',
    tag: 'Commerce Lessons',
    body: [
      'A sale is not the end of the story. It is the beginning of the relationship.',
      'After the first order or first month, check in with structure: what worked, what hurt, what to improve next.',
      'Deliver one small improvement quickly. Buyers remember momentum.',
      'Retention reduces the pressure to constantly hunt, which is especially helpful if you feel shy.',
      'Pocket spell: Now that you have used it for a bit, what is one thing you would change to make it smoother?',
      '5-minute drill: Create a simple post-sale checklist: onboarding, first success metric, first check-in, improvement plan.',
    ],
  },
  {
    title: 'Lesson 29: The Numbers That Matter',
    subtitle: 'Simple sales metrics for a technical mind.',
    tag: 'Commerce Lessons',
    body: [
      'You do not need a hundred metrics. You need a few that tell the truth.',
      'Track: new conversations per week, meetings per week, proposals sent, wins, losses, average deal size, cycle time.',
      'Use the numbers as feedback, not as a whip.',
      'If wins are low, increase conversations. If proposals are high but wins are low, improve qualification and proof.',
      'Technical people like this because it turns emotion into iteration.',
      'Pocket spell: I measure the process so I can improve the process.',
      '5-minute drill: Make a small weekly scoreboard. Update it every Friday. Pick one lever to improve next week.',
    ],
  },
  {
    title: 'Lesson 30: The Kind Seller',
    subtitle: 'Long-term wins come from steady, ethical behavior.',
    tag: 'Commerce Lessons',
    body: [
      'In the end, the most powerful magic in the castle is not showy. It is care: showing up, telling the truth, and doing what you said.',
      'A kind seller does not manipulate. They clarify. They guide. They protect the buyer from bad choices, even if it costs a short-term win.',
      'This is the style that fits shy and technical people best, because it is aligned with integrity.',
      'You can be ambitious without being aggressive. You can ask clearly without being rude.',
      'If you ever feel shame, return to the principle: clarity is kindness. You are offering a real option. The buyer has agency.',
      'Pocket spell: I will be direct and respectful. If this is not a fit, we will say so early.',
      '5-minute drill: Write your personal sales code in five lines. Read it before difficult conversations.',
    ],
  },
];

