export interface HogwartsStory {
  title: string;
  body: string[];
}

export interface HogwartsArticle {
  title: string;
  subtitle: string;
  body: string[];
  tag?: string;
}

export const HOGWARTS_STORIES: HogwartsStory[] = [
  {
    title: 'Quidditch Minute',
    body: [
      'A long match is never quiet. The crowd learns to read the game by its silences, the pauses where the Seekers rise and hover as if the whole pitch is holding its breath.',
      'Chasers and Beaters carve a rhythm that feels like a drumbeat. Every lap is a question about timing, and the answer changes with every turn.',
      'A Seeker does not chase all the time. A great Seeker watches, waits, and trusts the instinct that says the Snitch is about to appear.',
      'The wind on the pitch carries small signals. A flicker of gold near the east stands, a sudden hush behind the goal hoops, a Beater who looks up too quickly.',
      'When the Snitch is finally caught, the stadium erupts. The scorebook shows 150 points, but the story is the chase, the rise, and the moment the world went still.',
      'After the match, players walk off the pitch with grass on their robes and wind in their hair. It is not just a sport; it is a school ritual that teaches courage and clarity.',
      'If you want to feel the pulse of Hogwarts, stand by the pitch at dusk and listen to the training whistles carry across the lake.',
      'Up in the commentary box, the match becomes poetry. A voice turns chaos into narrative, and the crowd leans in as if words can steer a broom.',
      'Captains treat time like a spell ingredient. They slow the game with careful passing, then snap it forward with a sudden break that catches everyone mid-breath.',
      'Beaters learn restraint. The bat can feel like a hammer, but the best hits are measured: a gentle deflection, a warning shot, a perfectly timed save.',
      'Even on a losing day, the pitch teaches something worth keeping. You leave with sore hands, bright eyes, and the quiet certainty that you dared to fly.',
    ],
  },
  {
    title: 'First Night in the Tower',
    body: [
      'The first night in a Hogwarts tower feels like a dream that refuses to fade. The common room smells like wood, parchment, and the faint warmth of a fire that never quite dies.',
      'Students unpack trunks and set names into new routines. Some whisper, some laugh, some stare out the window as if the stars might answer back.',
      'The portraits talk louder at night, exchanging gossip as if they are catching up after a long day. It can feel strange, but the sound is comforting once you accept it.',
      'There is a moment, usually just before sleep, when the castle seems to settle. The corridors stop shifting for a while, the stairs grow quiet, and the wind softens.',
      'That is the moment when Hogwarts feels like it has opened a door for you. The school is not just a building; it is a living place that decides to make space for your story.',
      'Some students write letters home. Others stay up late talking about the Sorting. Everyone is a little tired and a little full of wonder.',
      'By morning, the tower feels less like a mystery and more like a home that knows your name.',
      'The dormitory has its own atmosphere: curtains that fall like gentle stage drapes, trunks tucked under beds, and a hush that arrives in waves as conversations fade.',
      'Somewhere below, a door clicks, then another. The castle makes small noises the way a ship does, and it is comforting once you realize it is simply alive.',
      'House ghosts, if they drift through, do it like familiar weather. They do not demand attention; they simply remind you that Hogwarts has been hosting first nights for centuries.',
      'You fall asleep not because you are done thinking, but because the day has been so full that even your wonder needs rest.',
    ],
  },
  {
    title: 'The Great Hall Morning',
    body: [
      'Mornings in the Great Hall begin with light. The enchanted ceiling mirrors the sky, and the tables glow with plates that seem to appear from memory.',
      'The room is full of small rituals. A friend passes the jam, a prefect scans the room, a student trades notes from last night, and every table hums with a different tempo.',
      'It is the only place where the whole castle feels gathered. The day is new, the voices are loud, and the air smells like toast and tea.',
      'Even the professors look different in the morning. The weight of the day has not yet arrived, and their smiles come a little easier.',
      'If you want a quiet seat, you do not sit far away. You sit in the middle and let the noise turn into a calm that only busy places can offer.',
      'When the owls sweep in, the room pauses. Letters land like small surprises, and the morning resets again.',
      'The Great Hall teaches that community can be loud and still feel safe.',
      'Steam curls from mugs like slow wand smoke. You can taste the day beginning: warm bread, sharp marmalade, the comfort of something simple and certain.',
      'Sometimes a student tries a spell under the table, very quietly, and a spoon trembles as if it is laughing. Someone notices, grins, and says nothing.',
      'Between bites, you overhear plans for Hogsmeade, whispers about homework, and small jokes that make the hour feel like a shared blanket.',
      'When you stand to leave, the room keeps humming without you. That is the magic: you belong, but you are not required to hold the whole place up.',
    ],
  },
  {
    title: 'Secrets of the Staircases',
    body: [
      'The staircases in Hogwarts do not obey fixed maps. They drift, pause, and choose their own routes, as if the castle is testing your patience.',
      'Students learn the patterns through stories. A third year shares a trick, a sixth year warns of a landing that always shifts after sunset.',
      'The best advice is to stop forcing the path. If you stand still, sometimes the staircase meets you halfway, like it has decided to be kind.',
      'Getting lost is part of the education. You learn the portrait of a knight who loves riddles, the corridor that smells like ink, the window that always catches the sunset.',
      'Over time, the stairs feel less like traps and more like teachers. They show you where you are in the castle, and where you need to be in your head.',
      'The castle does not want you to be perfect. It wants you to pay attention.',
      'If you are late to class, blame the stairs with a smile. The professors understand more than they admit.',
      'There are steps that dip like a sigh, and steps that vanish for a heartbeat to remind you not to run. The castle has a gentle sense of humor about haste.',
      'Students keep private maps that never truly work, scribbled with arrows and warnings. Half the ink is practical, half is superstition, and both are strangely accurate.',
      'Sometimes you meet someone else who is lost in the same place. You exchange a look and a laugh, and for a moment the staircase becomes a bridge instead of a puzzle.',
      'Once you stop fighting the castle, it stops fighting you. You arrive where you need to be, usually with a story you did not expect to collect.',
    ],
  },
  {
    title: 'The Owlery Letters',
    body: [
      'The owlery is tall and windy, a tower full of soft wings and quiet coos. It smells like parchment, dust, and the open sky.',
      'Letters feel heavier there. A student holds a message and tries to decide if it will be written with hope or honesty.',
      'Owls are patient. They watch and wait until they sense the right moment, then lift into the air with a confidence that feels like old magic.',
      'Sending a letter is a ritual of release. You watch it disappear into the clouds and trust that it will find its way, even if you do not know how.',
      'Many students visit the owlery just to stand among the feathers and the wind. It is a place where thoughts can fly for a while.',
      'The sound of wings is like a slow drum. It steadies the heart and clears the mind.',
      'Every letter begins at Hogwarts, but the owlery reminds you the world is still wide and waiting.',
      'Sometimes you bring a letter you never send. You read it once, fold it again, and let the wind take some of the worry out of your chest.',
      'Some owls deliver with flair, some with stubborn practicality. The personalities are obvious in how they perch, how they glare, how they accept a treat.',
      'A student can learn a lot here: how to choose words, how to hold silence, how to trust distance without turning it into loneliness.',
      'When you climb down, the air in the corridors feels still. You carry a new kind of courage—quiet, feather-light, and steady.',
    ],
  },
  {
    title: 'Library Night',
    body: [
      'The library changes at night. It becomes deeper and quieter, and the shelves seem to hold their breath when the candles dim.',
      'Walking the aisles after curfew feels like stepping into a memory. Each book hums with the lives of students who opened it before you.',
      'The silence is never empty. It is full of small sounds: a chair shifting, a page turning, the soft creak of a staircase outside.',
      'If you stay long enough, the library becomes less a place of study and more a place of listening. Answers do not arrive suddenly; they arrive gently.',
      'The portraits near the back shelves sleep with their frames tilted. Even the dust seems quieter here.',
      'When you finally leave, the corridor feels brighter. You carry a piece of the library with you, even if the book is back on the shelf.',
      'The night library teaches that knowledge can be calm as well as powerful.',
      'You learn the shape of your own attention here. Some nights you read like a sprint, other nights you read like a walk through snowfall—slow, careful, and strangely satisfying.',
      'A stack of books beside you becomes its own little fort. The candlelight makes the spines glow, and the world narrows to ink and breath.',
      'Every now and then, a shelf creaks as if it is stretching. You glance up, half expecting the castle to wink at you, and you smile at your own imagination.',
      'By the time you close the last book, your mind feels washed clean. You leave quietly, as if you do not want to wake the calm you just found.',
    ],
  },
  {
    title: 'The Restricted Section',
    body: [
      'The Restricted Section is the quietest part of the library. The air is cooler and the shelves stand a little closer, as if they are guarding their pages.',
      'Every book feels heavier here, not because of its size but because of what it asks from you. The words are older, the spells less forgiving.',
      'Students who enter with permission step carefully, aware that the wrong page could undo a week of careful work.',
      'It is a place of caution, but also of wonder. The knowledge is deep, and the curiosity that brings you here is part of your education.',
      'The lamps burn low, making the bindings gleam. It feels like the room is waiting to see if you are ready.',
      'You do not linger. You read, you learn, and you close the gate softly.',
      'Leaving the Restricted Section feels like stepping back into daylight after a long dream.',
      'A warning sign on a chain is never the real barrier. The real barrier is the discipline to read without hunger turning into recklessness.',
      'Some students take notes with shaking hands, not from fear but from awe. They realize, in a sudden quiet, that magic is older and deeper than schoolwork.',
      'Here you practice respect: for the rules, for the unknown, and for the part of you that wants to prove something too quickly.',
      'When you return to the brighter shelves, you feel grateful for ordinary textbooks. Not everything powerful needs to be touched.',
    ],
  },
  {
    title: 'Marauder Map',
    body: [
      'The map is a piece of mischief and precision, a parchment that breathes in ink. When opened, it reveals the castle as if it were a living diagram.',
      'Every name appears as a moving dot, every corridor as a shifting line. It is both a tool and a secret, passed in whispers between friends.',
      'Using it teaches responsibility. You can see everything, which means you must decide what not to do with what you see.',
      'The castle does not feel smaller with the map. It feels more alive, because now you can watch it move.',
      'There is a thrill in seeing a familiar name turn a corner. It makes the school feel like a story you can touch.',
      'When you fold it away, the ordinary corridors feel different, as if they are still murmuring under the paper.',
      'The map is not just about where people are. It is about how the castle breathes.',
      'The most surprising thing is not the movement, but the pattern. The map shows the rhythms: how crowds flow after dinner, how quiet gathers near the towers.',
      'You notice how often people circle back, how rarely anyone walks in a straight line. Hogwarts teaches wandering like a subject in itself.',
      'Sometimes you see a dot stop for a long time in a strange place and you realize that every student has private corners of comfort.',
      'Used wisely, the map is not a shortcut; it is a reminder that knowing a place also means caring for the people inside it.',
    ],
  },
  {
    title: 'Black Lake at Dusk',
    body: [
      'At dusk, the Black Lake turns to glass. The sky above and the water below become one wide canvas of fading color.',
      'The shore is a quiet place where students go to think. Sometimes the giant squid breaks the surface just to remind you that the lake is awake.',
      'The merpeople keep their distance, but you can sense them in the small ripples that appear without a breeze.',
      'On calm evenings, the reflections are so perfect that you feel like you are standing at the edge of two worlds.',
      'The air carries a soft chill, and the castle lights flicker on like stars pulled down to earth.',
      'It is a good place for promises. The lake does not answer, but it remembers.',
      'When you walk back, the sound of your steps feels like a quiet spell.',
      'The reeds whisper in a language you almost understand. You cannot translate it, but it soothes you anyway, like music heard through a wall.',
      'Sometimes someone else sits nearby, not close enough to intrude. You share the kind of silence that feels like friendship, even without names.',
      'If the water stirs, it stirs slowly. You learn to match that pace, to let thoughts move gently instead of crashing through your mind.',
      'The lake teaches a simple charm: pause, breathe, and let the world be wide for a minute.',
    ],
  },
  {
    title: 'Forest Edge',
    body: [
      'The Forbidden Forest begins where the lawns end. The trees are older than the school, and their shadows stretch farther than you expect.',
      'You can hear the forest before you enter it. The sound is soft, but it is alive, full of movement you cannot see.',
      'Students are warned to stay away, but curiosity always pulls. The edge is a place of stories, a place where courage meets caution.',
      'Standing there, you feel the weight of history. The forest has watched the school grow, and it has its own rules.',
      'Every leaf feels like an ear. Every branch feels like a reminder to step carefully.',
      'If you ever cross the line, remember to listen. The forest speaks quietly, but it speaks clearly.',
      'The edge is where lessons begin. The forest is where they deepen.',
      'The boundary itself feels enchanted, a subtle line in the air. On one side, the castle lights. On the other, darkness that is not evil, only ancient and unconcerned.',
      'You may spot hoofprints, or a feather that does not belong to any ordinary bird. The forest offers clues like riddles and expects you to remain humble.',
      'Courage here is not bravado. Courage is turning back when you should, and returning another day with wiser questions.',
      'Even from the grass, you learn respect. Some mysteries are meant to be approached slowly, with steady hands and quieter pride.',
    ],
  },
  {
    title: 'Hogsmeade in Winter',
    body: [
      'Hogsmeade in winter smells like snow and sugar. The roofs are white, the windows glow, and every shop feels like it has its own hearth.',
      'Students walk the streets with scarves pulled high, laughing as their breath becomes clouds. The village feels like a small celebration of warmth.',
      'Honeydukes is crowded with hands reaching for sweets, while the Three Broomsticks is loud with mugs and stories.',
      'The best part is the walk back. The castle rises from the snow like a lighthouse, and you feel grateful to see it again.',
      'The steps crunch underfoot, and the air tastes like a fresh start.',
      'Hogsmeade is not just a trip. It is a reminder that the world outside the school is still waiting for you.',
      'By the time you return, the warmth of the common room feels twice as good.',
      'In shop windows, enchanted ornaments twirl without strings. You catch yourself smiling at how easily magic becomes decoration when people feel safe enough to play.',
      'Someone buys a small pastry just to hold the warmth for a while. It is not hunger; it is comfort, the kind you can carry in your pockets.',
      'The snow makes every footstep sound honest. Even loud laughter feels softer, wrapped in cold air and scarf wool.',
      'When you reach the gates again, the castle looks both stern and welcoming. Like a teacher who wants you to be brave, but also wants you to come home.',
    ],
  },
  {
    title: 'Sorting Hat Legacy',
    body: [
      'The Sorting Hat sings new songs, but its work is the same: listen for who you are, not who you want to be seen as.',
      'It weighs courage, ambition, wit, and loyalty like a careful librarian weighing a rare book.',
      'Many students fear being placed in the wrong house, but the Hat cares about potential as much as present truth.',
      'Once the choice is made, the room erupts. It is the first time the school truly feels like it knows you.',
      'Some students are surprised by their house, but the house they join becomes part of them in ways they do not expect.',
      'Years later, students remember the moment the Hat spoke their house name. It is a small thunder that never fades.',
      'The Hat is old, but it is still listening.',
      'The song is part of the spell. It reminds everyone that the houses are not trophies; they are ways of living, each one a different kind of courage.',
      'The Hat’s pause can feel endless, but it is gentle. It is searching for the version of you that is truest when nobody is watching.',
      'Some students argue silently, pleading for one house or another. The Hat hears the plea, and also hears the fear beneath it.',
      'When the decision lands, it lands like a key turning. Not a cage, not a label—just a door opening into a place where you can grow.',
    ],
  },
  {
    title: 'Wand Lore',
    body: [
      'Wands are not tools; they are companions. The wood and core shape how the wand responds, and the bond grows with time.',
      'A wand has a temperament. Some are eager, some are cautious, some require patience before they show their strength.',
      'Students learn early that a borrowed wand feels different. The spell may work, but the feel is not the same.',
      'A true wand match feels like a door opening. The magic moves smoothly, without resistance.',
      'Small rituals of care matter. Cleaning the wand, storing it well, and treating it with respect change how it answers.',
      'When a wand chooses you, it is a quiet agreement. It says that you will grow together.',
      'A well loved wand carries stories in its grain, and the wizard knows them by heart.',
      'Beginners often grip too hard. The wand responds like a shy animal, tensing against fear. A softer hand invites a steadier spell.',
      'Even the sound of a wand matters: a gentle tap against a desk, a careful knock on a door. You learn that manners extend to magic.',
      'Over the years, your wand remembers you. It learns your timing, your breath, your habit of hesitation before you are brave.',
      'The bond is not romance. It is partnership—two forces learning to trust, correcting each other, and growing more honest with every cast.',
    ],
  },
  {
    title: 'Patronus Practice',
    body: [
      'Learning a Patronus is less about power and more about clarity. It begins with a memory that is simple, sharp, and true.',
      'The first attempts are often wisps, small clouds of light that vanish as soon as doubt creeps in.',
      'With practice, the light gathers. It becomes shape, movement, a creature that feels like a piece of your own spirit stepping forward.',
      'Casting a Patronus is a lesson in honesty. You cannot fake the memory, and you cannot force the form.',
      'The happiest memory is not always the strongest. Sometimes it is the truest and the smallest.',
      'When it finally works, the room changes. The air feels lighter, and the light stays a moment longer than you expect.',
      'A Patronus is not just protection. It is a promise to yourself.',
      'Some students chase grand memories and fail. Others find strength in something ordinary: a laugh with a friend, the smell of rain, a kind word that arrived at the right moment.',
      'The spell teaches you to hold joy without squeezing it. If you clutch the memory too tightly, it breaks. If you let it live, it shines.',
      'When the Patronus runs across the floor, it moves with confidence you did not know you possessed. It is like meeting your own courage in animal form.',
      'Afterward, the room feels warmer for a while. You leave with light under your ribs, as if the spell stayed with you in a quiet, steady way.',
    ],
  },
  {
    title: 'Common Room Fireside',
    body: [
      'The common room fire is the heartbeat of the house. After a long day, it pulls everyone back together.',
      'There are stories told by that fire that never reach the Great Hall. They are small, personal, and honest.',
      'Students learn to disagree without breaking the circle. That is the quiet magic of a shared space.',
      'When the fire crackles, it feels like the castle is listening. The room grows warmer, and the day feels softer.',
      'If you need a place to breathe, the common room will always let you sit by the fire a little longer.',
      'The glow on the walls makes the tapestries look alive. Even the shadows feel friendly here.',
      'By the time you leave for bed, the fire has turned your thoughts into steady embers.',
      'The armchairs become small islands of comfort. Someone curls up with a book, someone warms their hands, someone just watches the flames until their mind stops racing.',
      'House rivalries look different here. They soften into teasing, into shared snacks, into the understanding that your people are allowed to be flawed.',
      'Sometimes the talk turns serious, then quiet. The fire keeps burning, patient and steady, like it has heard it all before and can hold it without judgment.',
      'If you listen closely, you can hear the castle through the walls: distant footsteps, a door shutting, a portrait chuckling in its sleep. The world goes on, and you are safe inside it.',
    ],
  },
  {
    title: 'Greenhouse Rhythm',
    body: [
      'Herbology is a lesson in patience. Plants grow at their own pace, and the greenhouse teaches you to respect that tempo.',
      'The smell of soil and rain is calming. It makes the magic feel close, like it grows out of the earth itself.',
      'Students learn to listen to leaves the way others listen to spells. A plant will tell you what it needs if you pay attention.',
      'The greenhouse is warm even when the castle is cold. It is a small world that keeps its own weather.',
      'By term end, your hands are always a little dirty. That feels like a badge, not a problem.',
      'The quiet work of tending a plant teaches you that steady care is a kind of spell.',
      'The greenhouse is a place where magic feels slow, steady, and kind.',
      'There is always a hum of life: a vine reaching, a bud unfolding, a leaf turning toward the light like it is listening for instructions.',
      'Some plants react to feelings more than words. If you approach with impatience, they stiffen. If you approach with calm, they open to you.',
      'You learn that protection can be gentle. A charm that keeps pests away, a careful watering schedule, a hand held steady instead of rushed.',
      'On days when the castle feels loud, the greenhouse becomes a sanctuary. It reminds you that growth is allowed to be quiet.',
    ],
  },
  {
    title: 'Astronomy Tower',
    body: [
      'Astronomy is taught at night. The tower is cold, the sky is wide, and the stars feel like old friends.',
      'Students learn constellations and the way the moon pulls at tides. The lesson is as much about patience as it is about knowledge.',
      'There is a hush in the class that does not exist elsewhere. It is a shared awe, a kind of collective stillness.',
      'Looking down from the tower, the castle seems small. Looking up, it feels like part of something vast.',
      'The telescope turns, the charts rustle, and a quiet excitement runs through the group.',
      'By the end of the lesson, you feel grounded and expanded at the same time.',
      'The stars do not answer questions, but they make you ask better ones.',
      'Ink freezes a little in the cold, so you keep your hand close to the lantern between notes. Even that becomes part of the ritual, like the tower is teaching you to be present.',
      'Clouds sometimes roll in and ruin the lesson. On those nights, the professor teaches theory instead: how to navigate by memory, how to respect uncertainty.',
      'Some students are surprised by how calming the class is. You look up and feel your worries shrink, not because they vanish, but because they no longer fill the whole sky.',
      'When you walk back down, the stairwell feels warmer. You carry starlight in your thoughts like a small, private charm.',
    ],
  },
  {
    title: 'Hogwarts Kitchens',
    body: [
      'The kitchens are hidden below the Great Hall. House elves prepare feasts with a precision that feels like magic.',
      'The room is warm, full of movement, and scented with bread and herbs. It is a place of quiet pride and constant work.',
      'Students who find it are asked to be respectful. The elves do not seek praise, but they value kindness.',
      'The best meal in the castle is the one you do not see being made. That is the kind of magic the kitchens teach.',
      'Steam rises like fog, and the pans clatter in a rhythm that feels like a song.',
      'When you leave, you carry the smell of fresh bread like a secret.',
      'The kitchens remind you that care can be its own kind of power.',
      'Everything here is coordinated without shouting. A nod, a gesture, a tray moved at exactly the right time. It is teamwork so practiced it looks like enchantment.',
      'Students sometimes expect gratitude to be the currency. The elves teach a better one: respect, steadiness, and noticing the labor that keeps the castle gentle.',
      'A kettle whistles. Someone laughs. A dish polishes itself for a moment, as if joining the joy. The kitchen is not glamorous, but it is alive with purpose.',
      'When you climb back up to the Great Hall, you see the feast differently. Not as magic from nowhere, but as care made visible.',
    ],
  },
  {
    title: 'House Cup Night',
    body: [
      'The House Cup is a slow story told across the year. Points rise and fall with every class, every choice, and every late night effort.',
      'Winning feels sweet, but the real victory is the pride that lingers after the feast.',
      'The banners change colors, the cheers echo, and the tables are brighter than usual.',
      'Students remember the moment their house wins, but they also remember the moments they earned it.',
      'Some sit in silence, others celebrate loudly, and the castle seems to smile at all of them.',
      'By the time the feast ends, the points feel like a story, not just a number.',
      'The cup is a symbol, but the shared effort is the real prize.',
      'A first year watches the banners with wide eyes and decides, quietly, to try harder next term. An older student sees that look and smiles like they remember it.',
      'The speeches are short, but the feelings are not. Pride rises in the room like a tide, and even those who lost feel the dignity of having tried.',
      'After the feast, the castle corridors fill with music, then fade to whispers as everyone drifts back to their towers, carrying the year on their shoulders.',
      'In the morning, the banners are still there, and the lesson remains: effort matters, and community turns effort into something worth celebrating.',
    ],
  },
  {
    title: 'Portrait Gallery',
    body: [
      'The portrait gallery is a corridor of voices. Faces lean out of frames, trading gossip and opinions as you pass.',
      'Some portraits are helpful, others are demanding. They remember who was polite and who rushed by without a glance.',
      'At night, the portraits move between frames like neighbors visiting after dinner.',
      'If you are lost, a friendly portrait might point you the right way. If you are late, a grumpy one might make you pay for it.',
      'The portraits are part of the castle spirit. They add color, humor, and a small sense of being watched.',
      'To walk past them every day is to feel that Hogwarts is a place that notices you.',
      'The gallery teaches that even walls can have stories.',
      'Some portraits argue about fashion. Some argue about politics. Some argue about which staircase is the worst. Their debates are silly, but they make the corridor feel warm.',
      'A painting might call out your name with sudden friendliness, and you realize you have been seen enough times to be remembered.',
      'If you stop and listen, you catch little fragments of history: a duel from long ago, a feast from a forgotten era, a prank that became legend.',
      'In a castle made of stone, the portraits provide softness. They remind you that the past is not dead; it is chatting in the hallway, asking how your day went.',
    ],
  },
  {
    title: 'The Room That Listens',
    body: [
      'There is a room in Hogwarts that does not advertise itself. It appears when you need it, not when you want to show off.',
      'Some call it luck. Others call it ancient architecture. The truth is simpler: the castle pays attention.',
      'When you pace the corridor outside, your footsteps feel like a question. The stone waits to hear what you are asking for.',
      'If you need quiet, the door opens on a small sanctuary—soft chairs, warm light, a table ready for tea.',
      'If you need space, it becomes a long room for practice, with targets that reset politely and a floor that forgives clumsy landings.',
      'The room does not judge. It simply provides, the way a friend offers a blanket without making a speech about it.',
      'Students learn a private kind of magic here: admitting what they truly need and letting the castle answer.',
      'Afterward, you return to the corridors with steadier hands. The world has not changed, but you have.',
      'The room remains a secret, not because it is hidden, but because it is personal.',
      'In a school full of spectacle, the quietest enchantments often do the most good.',
      'If you ever find it, thank the castle with a calm breath and a soft closing of the door.',
    ],
  },
  {
    title: 'Prefects on Patrol',
    body: [
      'After curfew, the castle changes its posture. The chatter dissolves, and the corridors become long, listening hallways.',
      'Prefects walk with lanterns that cast gentle circles of light. The glow feels like a moving pocket of safety.',
      'Most patrols are boring, and that is the point. Peace is maintained by the quiet work of showing up.',
      'Sometimes they catch a student sneaking snacks, or giggling in a stairwell, and they choose kindness over drama.',
      'A firm reminder can be more effective than punishment. Hogwarts respects people who can hold boundaries without cruelty.',
      'The portraits are more awake than you’d expect. They offer opinions, warnings, and occasionally dramatic applause.',
      'Outside, the wind presses against windows. Inside, the lantern light keeps the castle from feeling too vast.',
      'Being a prefect teaches leadership in its smallest form: steady steps, patient eyes, and a calm voice at the right moment.',
      'When the patrol ends, the prefects return to their rooms with cold hands and warm pride.',
      'The castle feels grateful, in the way a place can feel grateful—quietly, and with fewer creaks in the dark.',
      'Even the night deserves caretakers.',
    ],
  },
  {
    title: 'The House Ghosts’ Debate',
    body: [
      'Every house has a ghost, and every ghost has an opinion. Put them in the same corridor, and you get a debate older than most textbooks.',
      'They drift in like weather, trailing stories in their wake. They speak with the confidence of people who have seen hundreds of students repeat the same mistakes.',
      'The debate starts politely: which house makes the best prefects, which house sings the loudest, which house wins with the most style.',
      'Then it becomes theatrical. One ghost complains about modern manners. Another insists the castle is nicer now. A third claims the staircases are worse.',
      'Students who overhear it pretend to be late on purpose. They linger behind a suit of armor and listen like it is a performance.',
      'The ghosts argue, but there is affection under it. They are guardians in their own peculiar way, proud of the living who keep the school going.',
      'A ghost might share a secret shortcut in the middle of a complaint, as if generosity is an accident they cannot help making.',
      'Sometimes the debate turns thoughtful. They remember classmates, lost friends, and the strange beauty of watching time pass from a frame of eternity.',
      'The corridor grows cold, then warm again when the ghosts drift away, their laughter fading like music down a stairwell.',
      'You walk on feeling oddly comforted, as if the school has extra layers of family you never asked for but are glad exist.',
      'In Hogwarts, even the past has a voice—and sometimes it is very funny.',
    ],
  },
  {
    title: 'Quillwork at Midnight',
    body: [
      'There is a special kind of quiet that arrives when homework becomes optional and you choose it anyway.',
      'Midnight quillwork is not about grades. It is about taking the day’s chaos and turning it into neat lines on parchment.',
      'A candle burns low. Ink smells sharp and clean. The room is warm enough to make your shoulders unclench.',
      'You write slowly, listening to the soft scratch of the quill like a metronome that steadies your thoughts.',
      'Outside, the wind runs along the stones. Inside, you are building something gentle: understanding, one sentence at a time.',
      'Sometimes you stop to stare at a word, wondering if it is spelled correctly. You smile at yourself and keep going.',
      'A roommate turns in their sleep. The castle creaks. The world remains alive, but it does not demand you perform.',
      'When the work is done, you feel lighter—not because the assignment is finished, but because you trusted yourself to do it.',
      'You cap the ink, blow out the candle, and let the darkness settle like a friendly cloak.',
      'Sleep comes easier when your mind has been given a clean place to rest.',
      'Midnight study is a quiet spell you cast on yourself: clarity, calm, and a promise that you can handle tomorrow.',
    ],
  },
  {
    title: 'Ravenlight Balcony',
    body: [
      'High in the castle, there are windows that feel like they were built for thinking. You stand there and the world becomes wide.',
      'Below, the grounds are a patchwork of shadows and moonlit grass. The lake holds the sky like a second ceiling.',
      'Up here, you can hear the castle’s heartbeat: distant footsteps, a faraway door, a portrait murmuring to itself.',
      'Students come to these windows when they need space. Not to escape life, but to see it from a calmer angle.',
      'The cold air clears the head. You breathe in and feel your thoughts line up like books on a shelf.',
      'Sometimes someone joins you without speaking. You share a quiet companionship built on the mutual respect of silence.',
      'You might talk about spells, or dreams, or nothing at all. The view does not require conversation to be meaningful.',
      'The best ideas sometimes arrive here, not as lightning, but as a slow dawn—soft, steady, impossible to rush.',
      'When you finally leave, the corridors feel easier. You have carried your mind into open air and brought it back gentler.',
      'The castle rewards anyone who seeks perspective instead of panic.',
      'A window can be a lesson: step back, look wider, breathe slower.',
    ],
  },
  {
    title: 'Hufflepuff Pathway',
    body: [
      'Some parts of Hogwarts feel like they were designed for comfort. Low corridors, warm light, and the smell of bread drifting from nowhere in particular.',
      'Along a certain path, plants lean toward the lamps as if they like being near people.',
      'Students walk here when they are tired. They walk slowly, letting the stones underfoot steady them.',
      'You notice small acts of kindness in this corridor: someone holding a door, someone offering a sweet, someone fixing a scarf for a friend.',
      'The magic here is not dramatic. It is practical, like a charm that keeps the air warm and the mood softer.',
      'Even the portraits seem gentler. They nod instead of shout, and their advice is surprisingly good.',
      'If you sit on a bench for a while, you can hear laughter from nearby rooms. It is the sound of belonging.',
      'This is where you learn that loyalty is not a slogan. It is daily behavior—showing up, helping, listening.',
      'You leave feeling repaired in small ways. Not suddenly happy, but steadier, like someone adjusted the balance in your chest.',
      'Hogwarts has many grand halls, but it also has hallways that exist simply to keep people well.',
      'Sometimes the best magic is the kind that makes ordinary life feel kinder.',
    ],
  },
  {
    title: 'Slytherin Underwater Silence',
    body: [
      'Deep in the castle, there are rooms that hold their quiet differently. The common room beneath the lake is one of them.',
      'Light comes through the water in slow green waves. It moves across stone walls like a living painting.',
      'The room feels private, protected. Conversations are softer, not from fear, but from the sense that the lake is listening.',
      'Students here learn to plan. They think a few moves ahead, not to be cruel, but to be prepared.',
      'Ambition in this space can feel elegant. It becomes a craft: setting goals, keeping promises to yourself, refusing to waste potential.',
      'When the water shadows pass, the room feels as if it is breathing. It is calming in a way you do not expect from a place so sharp in reputation.',
      'Some nights, a student sits alone and watches the lake creatures drift by. The view teaches patience better than any lecture.',
      'The quiet is not emptiness. It is focus, like a wand held steady before a spell.',
      'If you listen, you can hear the faintest creak of the castle above you, a reminder that even stone has layers of life.',
      'You leave with a kind of calm that is structured, intentional, and surprisingly warm.',
      'Not all peace is soft. Some peace is deliberate.',
    ],
  },
  {
    title: 'Gryffindor Passwords',
    body: [
      'Portrait passwords are a daily comedy. The password changes, the portrait complains, and someone inevitably forgets.',
      'In some towers, the portrait enjoys the power. It refuses entry unless you say the words with confidence and a bit of flair.',
      'Students practice in the hallway, whispering, then laughing, then trying again louder as if volume can substitute for memory.',
      'A friend arrives, out of breath, having sprinted up seven flights of stairs, and realizes the hardest part of bravery is admitting you forgot a word.',
      'The portrait sighs dramatically. It accepts the password, but offers a lecture about punctuality as if it has never been late in its painted life.',
      'Inside, the common room glows with warmth and noise. The whole ordeal becomes a story told by the fire five minutes later.',
      'These small moments matter. They turn rules into ritual and mistakes into laughter.',
      'A house known for courage learns something gentler too: you can be bold and still be kind about forgetting.',
      'By the end of term, the portrait knows the regulars by voice. It opens more quickly for the ones who greet it politely.',
      'The password is just a key. The real door is the feeling of arriving somewhere you are wanted.',
      'Even security in Hogwarts comes with personality.',
    ],
  },
  {
    title: 'The Express Northbound',
    body: [
      'Before Hogwarts is a castle, it is a train. A long red corridor of compartments filled with first-day nerves and second-year confidence.',
      'The Express smells like polished wood and snacks. The windows frame the countryside as if it is part of a storybook.',
      'Students trade introductions like spell ingredients: name, house hope, favorite subject, the fear they pretend not to have.',
      'Some sit alone at first, then soften when someone asks to share a seat. Friendships begin with the smallest permissions.',
      'Older students walk the corridor with easy laughter. They carry the calm of familiarity like an invisible cloak.',
      'At some point, the train curves and the light changes. A hush falls over a compartment as someone realizes they are actually going back.',
      'The closer you get, the more the air feels charged. Not with danger, but with possibility.',
      'Outside, hills pass. Inside, you rehearse who you want to be this year: braver, kinder, steadier.',
      'When the train finally slows, trunks clatter, and the corridor fills with movement. Everyone becomes a river flowing toward the same new beginning.',
      'The Express is a lesson in transition. It teaches you that you can carry your old self forward and still become someone new.',
      'A journey can be part of the magic, not just the way to it.',
    ],
  },
  {
    title: 'Dueling Club Lanterns',
    body: [
      'The dueling club meets in a room that smells faintly of chalk and old sparks. Lanterns hang low, turning the air golden.',
      'At first, everyone wants flashy spells. Then they learn the truth: the best duelers win with calm, not fireworks.',
      'You practice footwork until it feels like dance. Step, pivot, breathe, raise your wand without tightening your shoulders.',
      'A partner across from you looks nervous. You smile in a way that says, we are learning, not hunting.',
      'Shields come first. A shield spell is humble, but it changes the whole room. Suddenly, you feel safer, and safety makes learning faster.',
      'Someone miscasts and a small puff of smoke blooms like a harmless storm cloud. The room laughs, and the tension breaks.',
      'The instructor teaches restraint: choose a spell that fits the moment, not your ego.',
      'Over time, the club becomes a community. People cheer for improvement, not just victory.',
      'When you finally land a clean disarm, it feels less like triumph and more like clarity. Your body and mind agreed for a second.',
      'You leave with warm hands and steadier confidence, like you just practiced courage in a safe, structured way.',
      'Some battles are won long before they matter, in rooms lit by lanterns and patience.',
    ],
  },
  {
    title: 'The Clockwork Classroom',
    body: [
      'There is a classroom where the clocks do not all agree. Some run fast, some slow, some tick in silence as if they are thinking.',
      'Students assume it is a prank until the professor explains: time is a subject like any other—observe it, respect it, do not try to bully it.',
      'The lesson begins with listening. You close your eyes and learn the difference between a steady tick and an anxious one.',
      'Then comes the practice: small charms that nudge a pendulum, not to control time, but to understand how delicate it is.',
      'You learn that impatience is loud. The clocks respond to it by speeding up, as if mocking you.',
      'But calm has its own gravity. When you breathe slowly, the room becomes quieter, and the clocks settle into a gentler rhythm.',
      'Students leave with a strange sensation, like the day has more space inside it.',
      'You begin to notice where you rush for no reason: in hallways, in conversations, in your own thoughts.',
      'The professor calls it temporal manners. Do not interrupt the hour. Let it finish speaking.',
      'Back in the ordinary corridors, your steps slow a little. Not because you are tired, but because you learned that time can be treated with respect.',
      'Some lessons do not give you a spell. They give you a different way to live in your day.',
    ],
  },
];

export const HOGWARTS_ARTICLES: HogwartsArticle[] = [
  {
    title: 'First Week at Hogwarts',
    subtitle: 'A slow walk through corridors, candles, and new names.',
    tag: 'School Notes',
    body: [
      'The first week is all about orientation. You learn the cadence of the castle: which staircases like to wander, which portraits like to talk, and which corridors feel like they never end.',
      'Classes begin with small rituals. A professor writes the spell name on the board, then spends the rest of the hour teaching how intention and motion become a single thread.',
      'By the end of the week, you can find the Great Hall without thinking. The castle feels less like a maze and more like a friend.',
      'You also learn the pace of the day. Breakfast, lessons, the pause between classes, and the calm after curfew.',
      'It is a week of new names and new rhythms. The castle invites you in, one corridor at a time.',
      'You learn where to be early. Not because you fear punishment, but because arriving with a breath to spare changes the whole mood of a lesson.',
      'You discover small comforts: a window that catches the sunrise, a bench that is always warm, a corner in the library that feels like it was saved for you.',
      'By the weekend, you realize the castle has stopped feeling like a performance. It is simply your school now—mysterious, imperfect, and quietly welcoming.',
    ],
  },
  {
    title: 'Charms 101: Wandwork and Intent',
    subtitle: 'Why flicks matter, and why focus matters more.',
    tag: 'Lessons',
    body: [
      'Charms starts with control. You learn how a tiny tilt of the wrist can change the strength of a spell, and how a clear mind keeps your magic from wobbling.',
      'Every class ends with practice on everyday objects. Feathers, books, and glass jars become the training ground for trust between wizard and wand.',
      'The professor does not reward speed. The lesson is about steady movement and precise intent.',
      'Students learn to breathe before they cast. The breath becomes the start of the spell.',
      'When a charm finally works, it feels like the air agrees with you.',
      'The hardest part is consistency. A spell that works once is a lucky accident; a spell that works ten times is skill.',
      'Good wandwork looks simple from the outside. The real work is internal: attention, patience, and the willingness to start over without anger.',
      'Charms quietly teaches confidence. Not loud confidence, but the kind that says, I can try again, and I can do it with care.',
    ],
  },
  {
    title: 'Potions: The Long Simmer',
    subtitle: 'Patience, precision, and the quiet power of timing.',
    tag: 'Lessons',
    body: [
      'Potions is not about speed. It is about sequence, temperature, and the discipline to keep stirring even when nothing seems to happen.',
      'A good potion feels like cooking with a memory. One wrong step can make a mess, but one perfect stir can change the whole brew.',
      'Students learn to respect the cauldron. It does not rush, and it does not forgive shortcuts.',
      'The smell of herbs and smoke becomes familiar. By the end of term, you can name ingredients by scent alone.',
      'The best potioneers listen to the cauldron the way musicians listen to a melody.',
      'You learn to read the surface: a shimmer that means too hot, a dullness that means too cold, a spiral that means the mixture is finally ready to listen.',
      'Potions also teaches humility. Even talented students burn a batch sometimes, and the lesson is to clean up without sulking.',
      'When a potion succeeds, it feels earned in a very specific way: steady hands, clear steps, and the patience to let magic unfold at its own pace.',
    ],
  },
  {
    title: 'Defense: Dueling Basics',
    subtitle: 'Feet planted, shoulders relaxed, eyes sharp.',
    tag: 'Lessons',
    body: [
      'The first dueling lesson begins without spells. You learn to move, to read an opponent, and to keep your breath steady under pressure.',
      'When the wands come out, the room changes. It becomes a place of quick reflexes and calm decisions.',
      'A good duel is about control, not spectacle. The goal is to stay steady when everything around you moves fast.',
      'Students learn the value of a simple shield. It is not flashy, but it keeps you safe.',
      'A good duel ends with respect, not a victory lap.',
      'The professor emphasizes recovery: how to reset after a mistake, how to keep your mind from spiraling when you miss a cast.',
      'You learn to choose simple spells on purpose. A clean, well-timed defense often beats a complicated spell that arrives late.',
      'Defense is a lesson in temperament. The point is not to become aggressive; it is to become steady under pressure.',
    ],
  },
  {
    title: 'Flying Lessons: The First Lift',
    subtitle: 'Before the broom rises, your confidence must.',
    tag: 'Lessons',
    body: [
      'Flying starts on the ground. You stand straight, speak clearly, and wait for the broom to answer. It is less about force and more about trust.',
      'The first lift is unforgettable: a gentle rise, a sudden quiet, and a view of the grounds that makes everything feel possible.',
      'Most students land with shaky legs and a smile they cannot hide.',
      'The instructor repeats the same mantra: keep your eyes forward and your shoulders loose.',
      'Confidence is the true engine. When you believe, the broom believes too.',
      'You learn balance by feeling, not thinking. If you over-correct, the broom wobbles. If you relax, it steadies as if grateful.',
      'Falling is part of it. So is laughing afterward. The lesson is to get back on, not to pretend you never slipped.',
      'By the end of class, even the nervous students understand a secret: the sky is kinder when you meet it with calm.',
    ],
  },
  {
    title: 'History of Magic: Listening for Echoes',
    subtitle: 'The past is not dusty. It is layered.',
    tag: 'Lessons',
    body: [
      'History of Magic can feel slow until you realize it is a map. Every decision in the present has a root in the past.',
      'Students learn the names of old spells, old wars, and old mistakes. It is a quiet class that teaches patience and perspective.',
      'The professor may drift, but the stories still land. Some days the lesson is a warning, other days it is a reminder.',
      'The class teaches that power without memory is dangerous. Wisdom keeps you from repeating old mistakes.',
      'Sometimes the loudest lesson is the one that comes from a whisper.',
      'Taking notes becomes its own exercise in attention. You learn to pick out the thread of meaning inside a long, winding story.',
      'History teaches humility: you see how often people were certain they were right, and how often certainty became a mistake.',
      'The class is not exciting in the obvious way, but it is grounding. It makes you feel less alone in your own struggles, because every generation had theirs too.',
    ],
  },
  {
    title: 'Herbology: Greenhouse Rhythms',
    subtitle: 'Magic grows at its own pace.',
    tag: 'Lessons',
    body: [
      'Herbology is a lesson in timing. Some plants bloom at dawn, others only after a full moon.',
      'You learn to read soil, light, and leaf. The greenhouse becomes a place where magic feels alive and close.',
      'Every plant has a temperament. Some are gentle, some are stubborn, and some demand respect.',
      'Students learn to work with gloves and patience. A plant that bites teaches you to slow down.',
      'By term end, your pockets are full of seeds and small victories.',
      'The best work happens quietly. You water, prune, and wait, learning that care repeated over time is a spell all by itself.',
      'When a plant finally responds—unfurling, blooming, calming—it feels like a conversation you earned the right to have.',
      'Herbology teaches trust in slow progress. Not everything dramatic is meaningful, and not everything meaningful is fast.',
    ],
  },
  {
    title: 'Astronomy: The Wide Sky',
    subtitle: 'Stars teach patience.',
    tag: 'Lessons',
    body: [
      'Astronomy is taught at night. The cold air sharpens focus, and the sky becomes the chalkboard.',
      'Students learn that the stars are not just lights, but markers of time, direction, and ancient stories.',
      'The telescope becomes a quiet companion. You look, adjust, and look again until the picture settles.',
      'There is no rush in this class. The stars move at their own pace, and you must match it.',
      'The lesson ends quietly, with everyone a little calmer than when it began.',
      'Cloudy nights are part of the curriculum. You learn charts, theory, and how to stay curious even when the sky refuses to cooperate.',
      'Astronomy teaches a rare kind of confidence: the ability to admit you do not know yet, and to keep looking anyway.',
      'When you finally spot what you were searching for, the satisfaction is gentle and deep, like finding a familiar face in a crowd.',
    ],
  },
  {
    title: 'Transfiguration: Precision and Patience',
    subtitle: 'Small changes teach big control.',
    tag: 'Lessons',
    body: [
      'Transfiguration asks for discipline. You are not just casting a spell, you are reshaping reality in small, careful steps.',
      'The first lessons are simple: matchsticks, needles, and small objects that refuse to cooperate.',
      'Students learn that intent is not enough. They must also provide control and respect for the object.',
      'Mistakes are part of the process, but carelessness is not. The classroom rewards patience.',
      'When a change holds, the room feels quiet and proud.',
      'You learn to slow down before you cast, to picture the change with clarity instead of forcing it with frustration.',
      'Transfiguration teaches ethics in subtle ways. Just because you can change something does not mean you should do it thoughtlessly.',
      'When you finally succeed, the joy is precise: not explosive celebration, but a calm smile that says your skill became real today.',
    ],
  },
  {
    title: 'Care of Magical Creatures: Trust and Distance',
    subtitle: 'Courage is calm, not loud.',
    tag: 'Lessons',
    body: [
      'This class is muddy, loud, and full of surprises. Creatures do not care about your timetable, and that is part of the lesson.',
      'You learn that fear makes animals nervous, and calm makes them curious. The same is true for people.',
      'Some creatures are gentle, some are wild, and all of them are real. Trust is earned in small steps.',
      'Students learn to read a creature by its posture and movement. A raised tail, a lowered head, a shift in weight.',
      'You leave with a deeper respect for the living magic of the world.',
      'The professor teaches boundaries. Compassion does not mean recklessness; it means knowing when to step closer and when to step back.',
      'You practice watching without grabbing, listening without assuming. The creature notices, and its tension eases.',
      'This class teaches responsibility in a way books cannot. Life is not a diagram, and magic is not always neat. You learn to be gentle anyway.',
    ],
  },
  {
    title: 'Divination: Patterns and Patience',
    subtitle: 'Seeing is not the same as knowing.',
    tag: 'Lessons',
    body: [
      'Divination is a subject that asks for humility. The future is not a neat line; it is a field of possibilities that shift as you move.',
      'Students learn patterns first: symbols, seasons, the way the same story repeats in different costumes.',
      'Tea leaves are a lesson in attention. You learn to look without forcing meaning, to notice what stands out naturally.',
      'The professor reminds everyone that fear is a terrible translator. If you bring panic to a sign, you will only read panic back.',
      'Some days you see nothing, and that is fine. Learning to accept uncertainty is part of the skill.',
      'When you finally spot a pattern that feels true, it is not dramatic. It is quiet recognition, like remembering something you almost forgot.',
      'Divination teaches patience with the unknown—and respect for the parts of life that refuse to be controlled.',
    ],
  },
  {
    title: 'Quidditch Tactics: Lanes and Tempo',
    subtitle: 'How teams win without chasing chaos.',
    tag: 'Lessons',
    body: [
      'Quidditch looks wild from the stands, but good teams are structured. They control space the way a chess player controls squares.',
      'Chasers run lanes. They draw defenders out, then switch direction at the last second to open a clean path to the hoops.',
      'Beaters protect momentum. Sometimes the best hit is a quiet one that resets danger before it becomes a crisis.',
      'Keepers win with anticipation. They watch shoulders and eyes, not just the Quaffle, because intention shows before movement.',
      'Seekers must balance obsession with awareness. If you stare only for gold, you miss the game’s rhythm—and rhythm is where the Snitch likes to hide.',
      'The lesson is tempo: slow when you need control, fast when you have an opening, and always calm when everyone else wants to panic.',
      'Tactics are a form of kindness to your team. They turn effort into coordination, and coordination into confidence.',
    ],
  },
  {
    title: 'Enchanted Objects: Respect the Ordinary',
    subtitle: 'Why the smallest charms matter.',
    tag: 'Lessons',
    body: [
      'Some of the most useful magic is not flashy. It lives in objects that work a little better than they should: a self-filling quill, a bag that holds more than its size.',
      'Students learn that enchantment is responsibility. If you charm an object, you are making a promise about how it will behave.',
      'A charm must be stable. Unstable magic is like a wobbly ladder: it works until it suddenly doesn’t, and then it hurts someone.',
      'The class teaches maintenance. Enchanted objects need attention, recalibration, and sometimes rest.',
      'You learn to design with humility. If an object is meant to help, it should be simple enough to be trusted.',
      'By the end, you start noticing everyday magic everywhere: doors that close gently, candles that know when to dim, stairs that drift as if choosing kindness.',
      'The ordinary world becomes richer once you learn how much care is hidden inside it.',
    ],
  },
  {
    title: 'Study Craft: The Library Method',
    subtitle: 'Turning pages into calm.',
    tag: 'School Notes',
    body: [
      'Studying at Hogwarts is not just reading. It is learning how to live with a mind that wants to wander.',
      'The library method begins with environment: a steady chair, a warm light, a stack of books that feels achievable instead of threatening.',
      'Then comes pacing. You set a small goal—ten pages, one paragraph to summarize, a single spell to practice—so your mind has something real to hold.',
      'When distraction arrives, you don’t fight it like an enemy. You notice it, breathe once, and return to the line you were reading.',
      'You take breaks on purpose. A walk to a window, a sip of water, a minute of staring at the ceiling like it is an enchanted sky.',
      'This is how you make studying sustainable. Not heroic, not dramatic—just steady, gentle, and surprisingly effective.',
      'The best students are not the ones who never struggle. They are the ones who return again and again with calm determination.',
    ],
  },
  {
    title: 'House Points as Practice',
    subtitle: 'Why the scoreboard is not the lesson.',
    tag: 'School Notes',
    body: [
      'House points are a story told in numbers, and stories can be misunderstood.',
      'Some students chase points like trophies. Others resent them like unfair weather. Both miss the quieter purpose.',
      'Points are feedback. They are the school saying: that choice mattered, that effort was seen, that care changed the room.',
      'The healthiest way to treat the scoreboard is as practice. Do the work because it is right, not because it is rewarded.',
      'When points are lost, the lesson is not shame. The lesson is reflection: what happened, what can be done differently, how to repair trust.',
      'When points are earned, the lesson is not pride alone. It is gratitude—for teammates, teachers, and the self who chose to try.',
      'Over time, you realize the real house cup is the person you become by living the year well.',
    ],
  },
  {
    title: 'Exam Season: A Calm Plan',
    subtitle: 'How to prepare without losing yourself.',
    tag: 'School Notes',
    body: [
      'Exam season arrives like a storm on the horizon. You feel it in the library crowds, the late-night candles, the way everyone talks a little faster.',
      'The calm plan begins with honesty. List what you know, what you don’t, and what you keep avoiding because it scares you.',
      'Break the work into small blocks. Thirty minutes of focused practice beats three hours of anxious staring.',
      'Rotate subjects. Your brain likes variety, and variety keeps panic from settling too deeply.',
      'Sleep is part of the plan. A tired mind makes careless mistakes, and no amount of cramming can replace rest.',
      'Finally, remember the quiet truth: your worth is not your score. You are learning. You are growing. The work matters, but so do you.',
      'When you walk into an exam with calm breath and steady hands, you have already succeeded in something important.',
    ],
  },
];
